version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: vtc-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: vtcdb
      MYSQL_USER: vtcuser
      MYSQL_PASSWORD: vtcpass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-prootpass"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: vtc-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: vtc-backend
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - ./backend/.env
    environment:
      # Activate dev profile locally; override in prod deployment
      SPRING_PROFILES_ACTIVE: dev
      # MySQL
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/vtcdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: vtcuser
      SPRING_DATASOURCE_PASSWORD: vtcpass
      # Redis
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      # CORS for local frontend - read from backend/.env (or environment); fallback provided
      APP_CORS_ALLOWED_ORIGINS: "${APP_CORS_ALLOWED_ORIGINS:-http://localhost:5173,https://vtc-web.vercel.app}"
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        # Ensure API calls go to local backend by default
        VITE_API_BASE_URL: http://localhost:8080
    container_name: vtc-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      # map to 5173 to match local dev expectation
      - "5173:80"

volumes:
  mysql_data:
    driver: local
